version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.9.1-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - /etc/rabbitmq/
        - /var/lib/rabbitmq/
        - /var/log/rabbitmq/
    networks:
        - nodejs_app
  app:
    container_name: nodejs_app
    restart: always
    build: .
    ports:
    - '3000:3000'
    volumes: 
        - ./:/src
    external_links:
        - rabbitmq
    depends_on:
      - "rabbitmq"
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - nodejs_app
networks:
  nodejs_app:
    driver: bridge